# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
        - KnpUniversity\OAuth2ClientBundle\Security\Authenticator\Token\OAuth2PostAuthenticationToken

    google:
        enabled: true
        server_name: jja-dev.fr
        issuer: JJA_DEV_LAB
        template: admin/security/2fa_login.html.twig
